# Form implementation generated from reading ui file '.\MainUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 221)
        self.label = QtWidgets.QLabel(parent=MainWindow)
        self.label.setGeometry(QtCore.QRect(10, 10, 411, 20))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=MainWindow)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 331, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=MainWindow)
        self.pushButton.setGeometry(QtCore.QRect(350, 40, 71, 21))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=MainWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 331, 20))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(parent=MainWindow)
        self.groupBox.setGeometry(QtCore.QRect(9, 109, 411, 141))
        self.groupBox.setObjectName("groupBox")
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 201, 20))
        self.checkBox.setObjectName("checkBox")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(9, 80, 161, 22))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 70)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(6, 53, 141, 21))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FE2IO Python"))
        self.label.setText(_translate("MainWindow", "Please Enter your Roblox Username:"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.label_2.setText(_translate("MainWindow", "Status: Disconnected"))
        self.groupBox.setTitle(_translate("MainWindow", "Options"))
        self.checkBox.setText(_translate("MainWindow", "Quieten on Death"))
        self.label_3.setText(_translate("MainWindow", "Volume: 70%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
