# Form implementation generated from reading ui file '.\MainUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 221)
        self.label = QtWidgets.QLabel(parent=MainWindow)
        self.label.setGeometry(QtCore.QRect(10, 10, 411, 20))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=MainWindow)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 331, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.connect_button = QtWidgets.QPushButton(parent=MainWindow)
        self.connect_button.setGeometry(QtCore.QRect(350, 40, 71, 21))
        self.connect_button.setObjectName("connect_button")
        self.status_label = QtWidgets.QLabel(parent=MainWindow)
        self.status_label.setGeometry(QtCore.QRect(10, 70, 331, 20))
        self.status_label.setObjectName("status_label")
        self.option_gb = QtWidgets.QGroupBox(parent=MainWindow)
        self.option_gb.setGeometry(QtCore.QRect(9, 109, 411, 141))
        self.option_gb.setObjectName("option_gb")
        self.quieten_box = QtWidgets.QCheckBox(parent=self.option_gb)
        self.quieten_box.setGeometry(QtCore.QRect(10, 20, 201, 20))
        self.quieten_box.setObjectName("quieten_box")
        self.volume_slider = QtWidgets.QSlider(parent=self.option_gb)
        self.volume_slider.setGeometry(QtCore.QRect(9, 80, 161, 22))
        self.volume_slider.setMaximum(100)
        self.volume_slider.setProperty("value", 70)
        self.volume_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.volume_label = QtWidgets.QLabel(parent=self.option_gb)
        self.volume_label.setGeometry(QtCore.QRect(6, 53, 141, 21))
        self.volume_label.setObjectName("volume_label")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FE2IO Python"))
        self.label.setText(_translate("MainWindow", "Please Enter your Roblox Username:"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.status_label.setText(_translate("MainWindow", "Status: Disconnected"))
        self.option_gb.setTitle(_translate("MainWindow", "Options"))
        self.quieten_box.setText(_translate("MainWindow", "Quieten on Death"))
        self.volume_label.setText(_translate("MainWindow", "Volume: 70%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
